#!/usr/bin/env bash
# just runs the scan tracer
# directory of current script to make the command relative to script directory
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

PTSRC_DIR=$SCRIPT_DIR/../build/ptsrc
LIB_PT_DIR=$PTSRC_DIR/lib/pt

if (( $# < 1 )) ; then
    echo "Must specify test file"
    exit 0
fi

if `test ! -f $1`; then
    echo "$1 is not a file!"
    exit 0
fi

flag=$2

# ssltrace "ptc -o4 -t4 -L $LIB_PT_DIR $1" $LIB_PT_DIR/coder.def -e | grep "error"

if [[ "$flag" = "-ge" ]]; then
    # grep for error
    ssltrace "ptc -o4 -t4 -L $LIB_PT_DIR $1" $LIB_PT_DIR/coder.def | grep "error"

elif [[ "$flag" = "-o" ]]; then
    # print the tcodes and semantic oprations (like the sample provided in the tutorial)
    ssltrace "ptc -o4 -t4 -L $LIB_PT_DIR $1" $LIB_PT_DIR/coder.def | egrep "^ *[\.o%]"

elif [[ "$flag" = "-a" ]]; then
    # print everything
    ssltrace "ptc -o4 -t4 -L $LIB_PT_DIR $1" $LIB_PT_DIR/coder.def

elif [[ "$flag" = "-u" ]]; then
    # unstripped, does not do sed to it
    ssltrace "ptc -o4 -t4 -L $LIB_PT_DIR $1" $LIB_PT_DIR/coder.def -e

elif [[ "$flag" != "" ]]; then
    # pass the flag through
    ssltrace "ptc -o4 -t4 -L $LIB_PT_DIR $1" $LIB_PT_DIR/coder.def $flag
else
    # default behaviour
    # only shows emitted tokens
    ssltrace "ptc -o4 -t4 -L $LIB_PT_DIR $1" $LIB_PT_DIR/coder.def -e | sed -e 's/^ *//'
fi
